### ISSUE TITLE
Pop-up modal for each event

### ISSUE THREAD

**Issue by crismihailescu** [crismihailescu/socialMotivator#23]
- Pop-up looks aesthetic with a description, image, sign-up button, close pop-up button, and clean design
- It should be dynamic depending on which event you click on within different carousels
- Have some "cool" element that makes it more special, like a "read more" to expand the description, or image moving when mouse hovers over

**Comment by GaussianSums** [comment]
The modal is done, and works for the time being. Image change when hovered is a little rough atm.
