### ISSUE TITLE
Filtering activities by type

### ISSUE THREAD

**Issue by meinna** [crismihailescu/socialMotivator#3]
Issue with filtering activities by type. In props.activities.filter (line 26), d.type === { selectedActivity } is not returning true when expected. { selectedActivity } is showing expected result on its own and when hard-coded values such as 'Indoor' and 'Outdoor' replace { selectedActivity }, output is expected. So the issue is with comparison of d.type and { selectedActivity }.

**Comment by truzopus** [comment]
Fixed

**Comment by meinna** [comment]
Fix: commit 3914f31
